_gen_key() {
  local type=$1 key ks
  [ $# -eq 1 ] && ks="${type}_"
  key="/etc/ssh/ssh_host_${ks}key"
  if [ ! -e "${key}" ] ; then
    echo "Generating ${type} host key"
    ssh-keygen -t ${type} -f "${key}" -N ''
  fi
}

post_install() {
  _gen_key dsa >/dev/null 2>&1 || echo "gen_key dsa failed!"
  _gen_key rsa >/dev/null 2>&1 || echo "gen_key rsa failed!"
  . /usr/share/pacman/scm_install
}

post_upgrade() {
  . /usr/share/pacman/scm_upgrade
}
