#!/bin/sh
# iproute2 flush takes out all addresses including IPv6
# busybox ip doesn't have 'flush'
resolv_conf="/etc/resolv.conf"

case "$1" in
  bound|renew)
    /sbin/ip addr flush dev ${interface}
    /sbin/ip addr add ${ip}/${subnet} brd ${broadcast} dev ${interface}

    if [ -n "${router}" ]
      then
      echo "udhcpc: deleting routers"
      while /sbin/ip route del default dev ${interface} >/dev/null 2>&1
        do :
      done

      metric=0
      for i in ${router}
      do
        /sbin/ip route add default via ${i} dev ${inteface} metric $((metric++))
      done
    fi

    echo -n > ${resolv_conf}
    [ -n "${domain}" ] && echo domain ${domain} >> ${resolv_conf}
    for i in ${dns}
    do
      echo "udhcpc: adding resolver ${i}"
      echo "nameserver ${i}" >> ${resolv_conf}
    done
    ;;

  deconfig)
    /sbin/ip addr flush dev ${interface}
    ;;

  nak)
    echo "udhcpc: NAK received -- $message"
    ;;
esac

exit 0
