#!/usr/bin/env lua
-- debug.traceback = nil

function getpkgbuild(pkg)                     -- STRING
    local pkgbuildrepo = os.getenv('WORK')
    local repo = os.getenv('REPO')
    return pkgbuildrepo.."/"..repo.."/"..pkg.."/PKGBUILD"
end

function isdir(param)                         -- BOOLEAN
    local p, f = pcall(io.open, param, 'r')
    if f == nil then return false end
    local ok, error, code = f:read(1)
    f:close()
    if code == 21 then return true end
    return false
end

function isfile(param)                        -- BOOLEAN
    local p, f = pcall(io.open, param, 'r')
    if f == nil then return false end
    local ok, error, code = f:read(1)
    f:close()
    if code == nil then return true end
    return false
end

function table.contains(table, element)       -- BOOLEAN
    for _,value in ipairs(table) do
        if value == element then
            return true
        end
    end
    return false
end

function getdepends(param)                    -- TABLE
    local f = io.input(getpkgbuild(param))
    local pkgbuild = io.read('*all')
    f:close()
    local rdep = {}
    local cdep = {}
    local targets = {"makedepends", "depends"}
    local fulldepends = {}
    rdep["device-mapper"]           = "lvm2"
    rdep["gcc-libs"]                = "gcc"
    rdep["boost-libs"]              = "boost"
    rdep["libltdl"]                 = "libtool"
    rdep["libjpeg"]                 = "libjpeg-turbo"
    rdep["libgl"]                   = "mesa"
    rdep["libglapi"]                = "mesa"
    rdep["libegl"]                  = "mesa"
    rdep["ati-dri"]                 = "mesa"
    rdep["intel-dri"]               = "mesa"
    rdep["nouveau-dri"]             = "mesa"
    rdep["khrplatform-devel"]       = "mesa"
    rdep["xorg-server-xvfb"]        = "xorg-server"
    rdep["xorg-server-common"]      = "xorg-server"
    rdep["xorg-server-devel"]       = "xorg-server"
    rdep["poppler-glib"]            = "poppler"
    rdep["gtk-update-icon-cache"]   = "gtk2"
    rdep["nss-freebl"]              = "nss"
    cdep["gmp"]                     = "gcc"
    for _,y in ipairs(targets) do
        if string.find(pkgbuild, y) then
            for x in string.gmatch(string.match(pkgbuild, y.."=%b()"), "'([%w%-%_]*[%=%'%<%>]-)'" ) do
                local pattern = string.gsub(x, "-", "%%-")
                if table.contains(rdep, rdep[x]) then
                    x = string.gsub(x, pattern, rdep[x])
                end
                if not table.contains(fulldepends, x) and x ~= param and x ~= cdep[param] then
                    fulldepends[#fulldepends+1] = x
                end
            end
        end
    end
    return fulldepends
end

function getpkgdata(pkg, key)                     -- TABLE
    local f = io.input(getpkgbuild(pkg))
    local pkgbuild=io.read('*all')
    local _pkgname = {}
    local _fullname = {}
    local pkgdata = { pkgname=_pkgname, fullname=_fullname }
    local pkgver = string.match(pkgbuild, "[^%_]+pkgver=([%w%-%.%_]*)")
    local pkgrel = string.match(pkgbuild, "pkgrel=([%d]*)")
    f:close()
    if string.find(pkgbuild, "pkgbase") then
        local pkgnames = string.match(pkgbuild, "pkgname=%b()")
        for pkgname in string.gmatch(pkgnames, "'([%w%-%_]*)'" ) do
            _pkgname[#_pkgname+1] = pkgname
            _fullname[#_fullname+1] = pkgname.."-"..pkgver.."-"..pkgrel
        end
    else
        local pkgname = string.match(pkgbuild, "pkgname=([%w%-%_]*)")
        _pkgname[#_pkgname+1] = pkgname
        _fullname[#_fullname+1] = pkgname.."-"..pkgver.."-"..pkgrel
    end
    return pkgdata[key]
end

function getpkgbin(dir, pkg)                     -- STRING
    local bins = {}
    local binrepo = os.getenv('BINREPO')
    local repo = os.getenv('REPO')
    local dir = binrepo.."/"..repo.."/"
    local carch = { "any", "x86_64" }
    for _,pkgname in pairs(getpkgdata(pkg, "fullname")) do
        for _,arch in ipairs(carch) do
            if isfile(dir..pkgname.."-"..arch..".pkg.tar.xz") then
                bins[#bins+1] = dir..pkgname.."-"..arch..".pkg.tar.xz"
            end
        end
    end
    if next(bins) == nil then
       return false
    else
       return table.concat(bins, " ")
    end
end

do
    local builddir = os.getenv('BUILD')
    local outputdir = os.getenv('OUTPUT')
    local binrepo = os.getenv('BINREPO')
    local repo = os.getenv('REPO')
    local printf = function (...) io.write(string.format(...)) end
    local dirs = {}
    local binrepo = binrepo.."/"..repo.."/"
    local function getdep(param)                        -- STRING
        local deps = {}
        for _,dep in pairs(getdepends(param)) do
            if isdir(dep) then
                if getpkgbin(dep) then
                    deps[#deps+1] = dep
                elseif isdir(dep) then
                    deps[#deps+1] = dep
                end
            end
        end
        return table.concat(deps, " ")
    end

    printf("all:V: %s \n", table.concat(arg, " "))

    for _,pkg in ipairs(arg) do
        if getpkgbin(pkg) then
            printf("%s:V: %s %s \n", pkg, getpkgbin(pkg), getdep(pkg))
            printf("%s: %s \n", getpkgbin(pkg), getpkgbuild(pkg))
            printf("    rm -rf %s/* \n", builddir)
            printf("    cd %s \n", pkg)
            printf("    echo Started: $(date -uR)\n")
            printf("    makepkg --noconfirm -mci || $(echo Build failed: %s | /usr/bin/bti && exit 1)\n", pkg)
            printf("    echo Stopped: $(date -uR)\n")
            for _,oldpkg in pairs(getpkgdata(pkg, "pkgname")) do
                printf("    find %s -type f -regex '.*\\/%s-[0-9a-z\\.]*-[0-9]*-[0-9a-z\\_]*.pkg.tar.xz[\\.sig]*' -exec mv {} %s../backup \\;\n", binrepo, oldpkg, binrepo)
            end
            for _,newpkg in pairs(getpkgdata(pkg, "fullname")) do
                printf("    pushd %s\n", outputdir)
                printf("    echo Build finished: %s $(sha256sum %s-*.pkg.tar.??) | /usr/bin/bti\n", newpkg, newpkg)
                printf("    mv %s-*.pkg.tar.??{,.sig} %s\n", newpkg, binrepo)
                printf("    popd\n")
            end
        else
            printf("%s:V: %s \n", pkg, getdep(pkg))
            printf("    rm -rf %s/* \n", builddir)
            printf("    cd %s \n", pkg)
            printf("    echo Started: $(date -uR)\n")
            printf("    makepkg --noconfirm -mci || $(echo Build failed: %s | /usr/bin/bti && exit 1)\n", pkg)
            printf("    echo Stopped: $(date -uR)\n")
            for _,newpkg in pairs(getpkgdata(pkg, "fullname")) do
                printf("    pushd %s\n", outputdir)
                printf("    echo Build finished: %s $(sha256sum %s-*.pkg.tar.??) | /usr/bin/bti\n", newpkg, newpkg)
                printf("    mv %s-*.pkg.tar.??{,.sig} %s\n", newpkg, binrepo)
                printf("    popd\n")
            end
        end
    end
end


