post_install() {
  /usr/bin/alternatives --install /usr/bin/grep grep /usr/bin/ggrep 10
  /usr/bin/alternatives --install /usr/bin/egrep egrep /usr/bin/ggrep 10
  /usr/bin/alternatives --install /usr/bin/fgrep fgrep /usr/bin/ggrep 10
}

post_upgrade() {
  post_install
}

post_remove() {
  /usr/bin/alternatives --remove grep /usr/bin/ggrep
  /usr/bin/alternatives --remove egrep /usr/bin/ggrep
  /usr/bin/alternatives --remove fgrep /usr/bin/ggrep
}
